### ISSUE TITLE
Bug: creates shareable https link from ipns

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-companion#1012]
**Describe the bug**
I run an IPNS-only service: ipns://x86-64.archlinux.pkg.pacman.store

When I open the domain `x86-64.archlinux.pkg.pacman.store` in Brave with the browser plugin installed, I'll get correctly redirected to `http://x86-64.archlinux.pkg.pacman.store.ipns.localhost/` and the page is fetched from my local host.

When I now select "Copy Shareable Link", an http**s** link will be copied.

**Expected behavior**
The plugin should create http links, the assumption that every domain has to have https is wrong. When I would only run an http service the link wouldn't work.

Modern browsers are capable of using hsts preloading to determine automatically which domains are expected to be upgraded, so there's no need for https links.

**Screenshots**
![Screenshot_20210630_234714-1](https://user-images.githubusercontent.com/614929/124036025-aac62e00-d9fd-11eb-90e1-1d46c2f98a19.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave
 - Plugin-Version 2.19.1

**Comment by lidel** [comment]
- HSTS is not enough, as it won't protect the very first visit
  - due to this security risk, when you enter domain name without specifying protocol in address bar, modern browsers started defaulting to `https://` 
  
So we would not be comfortable defaulting all links to `http://`. 

In theory, we could test every time and see if `https://` works first, and if TLS is not available then (and only then) copy `http://`. This however, would send an unexpected HTTP request to a third party server, even when the user EXPLICITLY enabled redirect to the local gateway to avoid that. We also need to be careful about not breaking promises from our privacy policy.
