### ISSUE TITLE
meta http-equiv="x-ipfs-path" should redirect to ipfs (to mirror static sites lacking control over HTTP headers)

### ISSUE THREAD

**Issue by jsmaniac** [ipfs/ipfs-companion#1013]
**Is your feature request related to a problem? Please describe.**

I host a couple of small personal sites on GitHub pages, however that host doesn't allow changing the HTTP headers. I also have a site on the French host free.fr (a geocities-like host + ISP). It allows PHP (thus HTTP headers could be changed for PHP pages), but provides no mechanism to change the headers for static HTML files. Having to serve static HTML pages through PHP just to change the header does not make much sense, and would break caching etc. unless the caching headers were also added.

Since this is an issue with a couple of big hosts, I assume this is a common issue for static sites (which are the target for IPFS websites). It would be an easy job for a script to add an `<meta http-equiv="x-ipfs-path" content="/ipns/mysite.github.io/path/to/page" />` tag to each HTML file, using dnslink or a hardcoded ipns key, or even hardcode the ipfs hash of a specific version using `<meta http-equiv="x-ipfs-path" content="/ipfs/hash" />` (in which case the ipfs-hosted version would lack the hash and use ipns or no header at all).

Unfortunately, the IPNS companion ignores the `meta http-equiv="x-ipfs-path"` header, so a lot of static sites cannot also be hosted via IPFS without jumping through hoops with the existing HTTP host or switching to a different HTTP host altogether.

**Describe the solution you'd like**

If this does not cause some security issues, the IPFS companion should detect when the HEAD of the HTML page has been loaded, and check if it contains a `<meta http-equiv="x-ipfs-path" … />` tag. When the tag is present, the IPFS companion should stop the page from loading any further, and switch to the IPFS URL.

**Describe alternatives you've considered**

* contacting every host and convincing their IT department to allow configuring this specific HTTP header (unlikely to happen).
* switching to a different host (I'll do it myself, but it's a lot of hassle which reduces adoption)
* A link at the top of the page inviting users to browse the site using IPFS (visitors will likely ignore it)
* A JavaScript in the page's header which detects whether IPFS is available and changes `location.href` if that's the case (quite feasible but adds extra complexity, because it's necessary to correctly handle the history so that pressing the back button doesn't send the user in a loop, the IPFS detection mechanism needs to be reliable, JavaScript needs to be enabled on the client, if done incorrectly it will cause the page to flash while it gets reloaded or will slow down loading on non-IPFS browsers…).

Regardless of the option chosen above, redirecting to a specific gateway means that the gateway needs to still exist when the page is visited. It might be possible to manually set the `localtion.href` to `ipns://…/…`, which should auto-redirect to the local gateway without depending on any third party, though this relies on the presence of the IPFS companion or support for this URI schema from the browser. Detecting that the browser has IPFS capabilities can be done, but I'm not sure how easy it is to specifically check that the `ipns://…/…` URI schema is supported.

**Additional context**

Since this kind of redirection can already be achieved unconditionally with `<meta http-equiv="refresh" content="0;URL='https://mysite.github.io.some-ipfs-gateway.io/path/to/page" />` and conditionally with JavaScript, I assume that there are no security implications compared to a traditional HTTP header, but I haven't studied the issue with much scrutiny.

**Comment by lidel** [comment]
>  IPFS companion should detect when the HEAD of the HTML page has been loaded, and check if it contains a <meta http-equiv="x-ipfs-path" … /> tag.

Having support for `<link rel="duplicate" href="ipfs://…" />` would be nice for completeness with HTTP headers proposed in https://github.com/ipfs/in-web-browsers/issues/179.

Unfortunately, it is not something we can support in a browser extension:

- Streaming parsing of received payload is not possible in Chromium:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData#browser_compatibility
- Injecting JS on every page to check if HTML tag  is present would happen after the entire payload is fetched, which is way too late (entire payload is already received), and too expensive/invasive to be accepted (vendors discourage injecting JS to every page due to performance impact).

Afraid there is nothing we can do in Companion  – closing. 

FYI alternative approaches that may work for you:
 - One  reliable solution for providing  IPFS hint that is independent of your HTTP hosting is [DNSLink](https://docs.ipfs.io/concepts/dnslink/). 
It works even when HTTP server is down, IPFS-capable clients are able to recover and load the content path.
- Second solution, when you can't set DNS nor HTTP headers, is to put your subresource use a path that follows IPFS convention:  `/ipfs/{cid}` → IPFS Companion will detect valid CID and redirect subresource request to local gateway, respecting user preference.

> It might be possible to manually set the localtion.href to ipns://…/…, which should auto-redirect to the local gateway without depending on any third party,
>   I'm not sure how easy it is to specifically check that the ipns://…/… URI schema is supported.

I believe this is  something you want to avoid. Webpages should not do any redirects or protocol upgrade. This is user hostile behavior because there is no way for a page to know user preference or the address of gateway they wish to use.  

This should happen in User Agent: a browser extension (like Companion) or browser itself (like Brave) are the only places where a redirect can be executed in a way that respects user choice.

**Comment by jsmaniac** [comment]
I'm already using DNSLink for my own domain, however many sites are still hosted as foobar.free.fr or foorbar.github.io.

The `/ipfs/{cid}` subpath is however a good solution :) for sites hosted online (not for local file://… HTML files). It does add an unsightly hash in traditional HTTP URL which is unfortunate for clients which do not support/want IPFS, however the HTTP URL could be prettified using `window.history.pushState`.

I like this solution because if one bookmarks / links to the HTTP URL, it stays reachable via IPFS even if the original host is down or the domain name has changed hands. Prettifying the URL with `history.pushState` would negate this extra advantage, so there's a tradeoff (implicit redirection to IPFS for pretty URLs vs resilient explicitly-IPFS url).

> I believe this is something you want to avoid. Webpages should not do any redirects or protocol upgrade. This is user hostile behavior because there is no way for a page to know user preference or the address of gateway they wish to use.

Thanks for the heads-up, that's a good point (the gateway would be selected by the browser based on user preference for an `ipfs://cid` URL, but the user might not wish to auto-switch to IPFS URLs at all, even if the browser has the capability to do so).
