### ISSUE TITLE
Back Up IPFS Node

### ISSUE THREAD

**Issue by frogdesk** [ipfs/ipfs-companion#1019]
**Is your feature request related to a problem? Please describe.**
I am very nervous about losing my IPFS node because I cannot figure out a way to back it up other than saving all the individual files, and I am nervous I won't pin them in the right way next time because sometimes pinning produces a IPFS path, and other times it produces an IPFS path with a filename on the end of it.

**Describe the solution you'd like**
I would really like an easy way to back up all my IPFS node to a file or zip so it can be restored if anything goes wrong.

**Describe alternatives you've considered**
I have backed up every individual file to a folder, and can re-pin them if necessary, but this is highly manual and also prone to issues with the paths being different as mentioned.

**Additional context**
If I am missing something and this is a feature, my apologies, please document it better as I have searched far and wide :P

**Comment by lidel** [comment]
In the future, please open a topic at our discussion forums, more people will see your question: https://discuss.ipfs.io/c/help/13

But since I've aready read it, here are some options which you may find useful:

## Automatic: set up MFS auto pinning

If you are ok with  automatic  backup of everything in your Files (MFS) then you could use automatic pinning feature.
There is a GUI in ipfs-webui for enabling it:

> ![2021-09-10_20-56](https://user-images.githubusercontent.com/157609/132903801-45a76140-a5da-4679-b9ed-2423ed6a696b.png)

Or you could enable it manually via go-ipfs config via [`Pinning.RemoteServices: Policies.MFS`](https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#pinningremoteservices-policiesmfs).

If you are not familiar with concept of pinning services, read https://docs.ipfs.io/how-to/work-with-pinning-services/ first.

## Manual: DAG import/export

If you want to back up everything in MFS (ipfs-webui → Files) manually to a single file:

```console
$ ipfs dag export $(ipfs files stat / | head -1) > mfs_backup.car
```

Then you can restore it by importing and then copying CID reference to MFS on the new node:
```console
$ ipfs dag import mfs_backup.car
Pinned root	bafyCID	success

$ ipfs files cp /ipfs/bafyCID /restored_backup
```

You don't need to do entire MFS, you can export/import specific subdir or a file this way as well.
