### ISSUE TITLE
Automatic gateway selection

### ISSUE THREAD

**Issue by hazae41** [ipfs/ipfs-companion#1024]
## **Is your feature request related to a problem? Please describe.**
Sometimes, the public gateway "A" may not have the requested content, but another public gateway "B" have it.

This results in a delay for A to:
1) find that B have the content
2) download the content from B

## **Describe the solution you'd like**
So instead of having only one gateway to ask, we could have a set of public gateways, and the extension would ask each of them if they have the content (using a HEAD request). The first gateway to answer "yes" serves the content.

## **Additional context**
I already used this method in a software and the time to first byte is near instant. Plus, the usage of HEAD requests is okay for performances/bandwidth.

**Comment by lidel** [comment]
I like the premise of making content resolution more robust, however afaik the HEAD request still triggers CID lookup and fetch on every gateway, which is not a nice behavior, because you essentially waste resources across multiple gateways, and use only one of them :grimacing: 

We could implement this multi-gateway-recovery feature  if we had a way to detect if a CID is present on remote gateway without triggering fetch if it is not.
That way, if no gateway has the content, we use random one.

Potential candidates are `dag stat` and `block stat` with `--offline` flag, which will fail instantly if requested CID / DAG is not present in local datastore:

```console
$ curl -X POST "http://127.0.0.1:5001/api/v0/block/stat?arg=${CID}&offline=true"
{"Message":"blockservice: key not found","Code":0,"Type":"error"}
```

**Comment by hazae41** [comment]
@lidel The good part of over-fetching is that the content will be there next time for a closer user.

It will also improve data redundancy across the IPFS network. That is the goal of IPFS isn't it?

**Comment by lidel** [comment]
Gateways are not pinning services, they don't  even come with deterministic caching  :)

Gateways do not pin content, they run with GC enabled, and some of the biggest gateways do not even announce cached CID on DHT, because cache gets evicted too fast to be useful to the network.

My understanding is that if everyone starts abusing gateways this way, you artificially increased their load which diminishes any caching benefit (cache gets filled faster, GC gets triggered faster, DHT is filled with dead provider records → IPFS lookup is slower due to dead records trashing).

**Comment by hazae41** [comment]
Thank you for the explanation, I didn't see it that way

**Comment by lidel** [comment]
I'm closing this issue but feel you could fill a new one for a limited scope.
We could keep a list of public gateways and if there is no local IPFS node running, use them as failover when some IPFS gateway down or returning HTTP Errors such as 504,  451 etc.
