### ISSUE TITLE
ipfs resolve -r[/ipns/*](*): no link named * under *  &  context deadline exceeded

### ISSUE THREAD

**Issue by slrslr** [ipfs/ipfs-companion#1061]
**Describe the bug**
On Linux Debian 11 with latest $ ipfs --version
ipfs version 0.12.0 (go-ipfs)
I am having Firefox-ESR web browser with companion addon 0.12.0

When i open https://piped.kavin.rocks/watch?v=ZRAStnf4AMA then i see errors mentioned in the title. Issue was also previously submitted to https://github.com/TeamPiped/Piped/issues/855

**Comment by lidel** [comment]
You see the error:
```
ipfs resolve -r /ipns/piped.kavin.rocks/watch: no link named "watch" under QmTX4KoUH3bWJVCdgACNkDiqB8gmDyTZYGApeDop9Whf7A
```
because DNSLink points at `QmTX4KoUH3bWJVCdgACNkDiqB8gmDyTZYGApeDop9Whf7A` and that directory has no `/watch` directory:

```console
$ ipfs ls /ipfs/QmTX4KoUH3bWJVCdgACNkDiqB8gmDyTZYGApeDop9Whf7A/watch
Error: no link named "watch" under QmTX4KoUH3bWJVCdgACNkDiqB8gmDyTZYGApeDop9Whf7A
```


Most likely, the website owner registers a service worker that handles `/watch` and forgot to include `/watch/index.html` to ensure links work when loaded from local IPFS version. 

You should explain this in https://github.com/TeamPiped/Piped/issues/855, there is nothing wrong with ipfs-companion.
