### ISSUE TITLE
CI windows-tests failing

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/ipfs-companion#1071]
@lidel why did the windows-latest tests fail on the merge of https://github.com/ipfs/ipfs-companion/pull/1064#event-6197372346? we need to address that.

1. https://github.com/ipfs/ipfs-companion/runs/5412550268?check_suite_focus=true
2. https://github.com/ipfs/ipfs-companion/runs/5412542573?check_suite_focus=true

**Comment by lidel** [comment]
- ipfs-companion was not updated for a while and Node / NPM ecosystem is very sensitive to entropy

- We will rewrite companion fanyway due to #666  (wip in https://github.com/ipfs/ipfs-companion/pull/1044), but that may not happen until the end of this year (we need to finish MV3 work before 2023, Google started removing MV2 support already).

  - If we want to fix this before MV3 ships, then we would have to finish https://github.com/ipfs/ipfs-companion/pull/1054 where I already updated dependencies and webpack build (sadly got distracted by higher priority work and never finished it)

**Comment by lidel** [comment]
Resolved by #1094
