### ISSUE TITLE
Rename to Kubo-Companion

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/ipfs-companion#1086]
Go-ipfs will be [renamed](https://github.com/ipfs/go-ipfs/issues/8959) to Kubo, and I think it would make sense to rename ipfs-companion, too.

### Rationale

The idea behind the rename of go-ipfs was, to keep the "namespace" clean and allow other applications to refer to IPFS as a network, protocol, distributed storage – not as a specific application.

It's like Apache and Nginx are Servers for http(s), but there's no Server called go-http as reference implementation.

Following this argument, it makes sense to allow other applications to make browser plugins or other companion applications for ipfs without referring to this application.

**Comment by lidel** [comment]
The purpose of IPFS Companion is to **bring IPFS features** (`ipfs://` and `ipns://` addressing, redirect to a gateway of user choice, link rot recovery) to web browsers – **not to be a Kubo client**.

It happens to use Kubo (go-ipfs) right now, because it is the best implementation for the job. 
That may change in the near future.


* we are forced to rewrite Companion because of Google's Manifest V3 decision (#666)
  * this will include replacing peer count with more useful indicator (https://github.com/ipfs/ipfs-companion/issues/662)
* only real reasons why Companion is using RPC at `/api/v0`:
  * quick file import (can be replaced with writable gateways)
  * DNSLink resolution (can be replaced with HEAD request to gateway)
* we are working towards implementation-agnostic gateway specs being the interface, and removing the need for using implementation-specific RPC like `/api/v0` from legacy go-ipfs
  * this will allow people to point IPFS Companion at any gateway and get the same experience, as long implementations (like Kubo) follow the spec

Due to this, I'm closing this as not planned.

**Comment by RubenKelevra** [comment]
Alright, thanks for the clarification :)
