### ISSUE TITLE
I constantly get ipfs api accessible/inaccessible chrome notifications when i run something cpu and memory intensive on all cores.

### ISSUE THREAD

**Issue by kotenok2000** [ipfs/ipfs-companion#1091]
**Describe the bug**
I  get ipfs api accessible/inaccessible chrome notifications when i run something cpu and memory intensive on all cores.
**To Reproduce**
1. install ipfs desktop
2. Run boinc on all cores and run virtual machine with 4 gb ram allocated.
3. install ipfs companion and open lots of tabs.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.22000.856]
 - Browser: chrome
 - Version: 104.0.5112.102 

**Additional context**

**Comment by SgtPooki** [comment]
Thanks for submitting this issue @kotenok2000. 

I believe this issue is with chrome or your computer specifically and not ipfs, but we may be able to investigate further if you can provide further information: 

* Can you share your total memory allocation when these errors occur? 
   * Do you have any extra memory? 
   * Are other network operations or browser plugins working when in this state?

**Comment by kotenok2000** [comment]
No. I have 16 gb and 91% is used. 
It happens when browser lags.

**Comment by kotenok2000** [comment]
What more information do you need?

**Comment by SgtPooki** [comment]
@kotenok2000 Thanks for that information.

It seems like you're running out of resources for what you're trying to do. ipfs-companion has logic where it polls the running ipfs daemon every [3 seconds](https://github.com/ipfs/ipfs-companion/blob/cc5c8698184fe5518eb3f1c171bde6010360fd6f/add-on/src/lib/options.js#L29), to make sure the daemon is available. I imagine updating that logic to slow the polling time as requests are returning more slowly could help solve your and any others' similar issues. 

However, for now, you can change that setting in ipfs-companion settings. See if that helps resolve your issue. 

You could also start up the `kubo` daemon instead of IPFS Desktop too, to see if this helps your more resource intensive usecase. 

I'll leave this issue open for making that polling logic smarter, but this is blocked until #666 is resolved.

**Comment by lidel** [comment]
It is unblocked (merged #1054). 

@whizzzkid  thoughts on solving the underlying annoyance and stopping online/offline notifications?

We could either:
- stop showing system notification when node state changes by [removing `notify` calls from this function](https://github.com/ipfs/ipfs-companion/blob/main/add-on/src/lib/ipfs-companion.js#L526-L537)
- (if you feel it is useful at all) add a new toggle on Options page :gear:, but it should be turned off by default.

My vote would be to simply remove these two notifications – user feedback has been consistent that they are annoying.
