### ISSUE TITLE
Pin, Copy canonical address, and Copy gateway url, are no longer in context menu

### ISSUE THREAD

**Issue by djdv** [ipfs/ipfs-companion#294]
In an older version, while you were looking at IPFS content, you had the option to pin the hash or copy the locations of it from the context menu, it seems like this has disappeared. It still remains in the panel for the extension but not in the context menu. 

Here's an image of me looking at an image of the old context menu with the new context menu on the right.
![meta](https://user-images.githubusercontent.com/13862850/31578459-9ddae7a2-b0ef-11e7-9507-e2f2981ff584.png)

I'm curious if this was removed intentionally or if it is something else. I used this feature quite a bit.

**Comment by lidel** [comment]
Thank you for reporting this, I agree it was a useful feature.

It was done intentionally, had to make compromises due to limitations of WebExtension APIs and cross-browser compatibility at a time. It was not possible to programmatically add/remove items depending on tab context in a way that works in both Firefox and Chrome.

In effort to keep the feature alive and working in both browsers I **moved mentioned items from right-click context menu to the popup menu under browser action**:

> ![](https://addons.cdn.mozilla.net/user-media/previews/full/189/189681.png?modified=1507914587)

That being said, I revisited documentation and we might be able to restore old behavior, at least under Firefox. 

Let's keep this ticket open until I find time to play with APIs supported by Firefox 57.

**Comment by lidel** [comment]
@djdv I was able to restore tab-aware options for copying address to clipboard:

> ![2017-10-15-212603_605x401_scrot](https://user-images.githubusercontent.com/157609/31588240-84c20d26-b1ef-11e7-9d3e-181d91c62790.png)

What is the most important: I've found a way to make it work under both Chrome and Firefox.
Pinning is more complex, I'll look into adding it later this week.

If you want to test it right now, you can install [v2.0.14beta1](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/versions/beta) from beta channel.

**Comment by djdv** [comment]
@lidel 
Perfect, thanks!

**Comment by djdv** [comment]
However, I suppose I should leave this open until the Pin feature is decided on. (The important one for me personally was just the gateway url)

**Comment by lidel** [comment]
@djdv [v2.0.14](https://github.com/ipfs/ipfs-companion/releases/tag/v2.0.14) just landed 🚀 

Pinning turned out to be too expensive and will have to stay in browser action popup.
But I managed to add some smarts: if you right click on graph image [here](https://ipfs.io/ipfs/QmNZiPk974vDsPmQii3YbrMKfi12KTSNM7XMiYyiea4VYZ/example#/ipfs/QmP8WUPq2braGQ8iZjJ6w9di6mzgoTWyRLayrMRjjDoyGr/graphmd/README.md) then copied links will be of the image itself, not the parent page.  Hope its useful.
