### ISSUE TITLE
Improve dnslink resolution

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/ipfs-companion#69]
This would prevent possible delay of loading the page when DNS is slow (on bad connections DNS resolution can take few seconds).

So start loading page via normal HTTP and start resolving dnslink, if dnslink is available terminate normal HTTP connection and redirect to local gateway.

**Comment by lidel** [comment]
Current SDK  provides two [HTTP events](https://developer.mozilla.org/en-US/docs/Observer_Notifications#HTTP_requests) (same for the [future one](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/WebRequest.jsm#onBeforeRequest)) 
that we can hook into _before_ request is made:

> - `http-on-modify-request` 	Called as a http request is made. The channel is available to allow you to modify headers and such. 
> - `http-on-opening-request` 	Similar to http-on-modify-request, but called earlier (synchronously during the channel's asyncOpen() call), and some channel atttributes (proxyInfo) may be missing.  Use only if your observer must be called before asyncOpen returns.
> 
> – https://developer.mozilla.org/en-US/docs/Observer_Notifications#HTTP_request

Currently, all the redirect logic of this addon is in `http-on-modify-request`  handler.

I guess we could hook into earlier `http-on-opening-request` and only check if host is in cache. 
If not,  do an _asynchronous_ dnslookup with a callback that puts the result in cache.
Then in `http-on-modify-request` we would just check the cache.
Result:  no slowdown caused by synchronous lookups or slow DNS/network.

There is a risk of dnslink lookup taking longer than the delay between those two events, but it would be only for an initial cache miss (and we could save cache between browser restarts).
Not sure if we can do anything more with these APIs.

Should I give it a try?

**Comment by the8472** [comment]
At the very least we could do an async XHR and `suspend` the nsIRequest instead of blocking the main thread waiting for a response and `resume` the request once we got a response. This way at least the UI stays responsive.

**Comment by lidel** [comment]
Thank you @the8472, it was a very good insight. 

- dnslink lookup is now done asynchronously
- lookup is executed only if  DNS support is enabled, record was not found in cache and API is up
- request is suspended until dnslink lookup callback is fired

**Comment by lidel** [comment]
Reopening: I feel it may be a good idea to revisit this in WebExtension rewrite and see if something similar can be introduced.
