### ISSUE TITLE
meta-parm for not being under fs:/

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/ipfs-companion#88]
It breaks for example anuglar.js.

Example: access fs:/ipns/glowing-bear.ipfs.ovh
It might redirect to http already but it is other bug.

**Comment by the8472** [comment]
Analyzing what causes this issue and whether it may be fixed should be a saner approach than simply disabling the feature.

**Comment by Kubuxu** [comment]
It is but getting things to work with it will be a really long process.

**Comment by the8472** [comment]
Well, i'm interested in what fails, but the source is minified and auto-prettify doesn't seem to work. Can you try it without minified code?

**Comment by lidel** [comment]
I think we should fix underlying issue: adding custom HTML hints which are only used by one browser sounds like an nightmare from IE 6 times :cry: 

As for the problem at hand, `glowing-bear.ipfs.ovh` does not work any more, but my intuition is that the problem is caused either by [fs:→https: redirect](https://github.com/lidel/ipfs-firefox-addon/issues/87) or [no-cookies for /ipfs/ paths](https://github.com/lidel/ipfs-firefox-addon/issues/72).

Until fixed, there is a note about `fs:` breaking JavaScript on some pages (cf8bbc4).

**Comment by Kubuxu** [comment]
sorry for glowing-bear.ipfs.ovh not working but my IPFS suffer hangs so I can't run it. It will come back when underlying issue is solved.

**Comment by lidel** [comment]
Not that we closed #20 this is no longer reproducible: we don't have custom protocol anymore, only a set of hacks that redirect to HTTP -- see #164 for more details.

I am closing this one.
If similar problem surfaces again, it should be a new issue (for webextension version).
