### ISSUE TITLE
Add share.ipfs.io to be shipped with companion

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-companion#988]
[This reaction](https://twitter.com/adjyleak/status/1372152033248165888?s=21) reminded me, why not have https://share.ipfs.io a click away from IPFS Companion? Users would love it! (I would! :D)

**Comment by jessicaschilling** [comment]
If I recall correctly, this was discussed a while back but at the time the tool was a bit too beta - but that was, I believe, the only reason not to. Hoping that @lidel can confirm/deny/amend that recollection.

**Comment by lidel** [comment]
The main (only?) reason why we have custom import UI in Companion is that it has to work in "offline/restricted " contexts (limited WAN connectivity, censored DNS/network environments etc). 

Right now, we import to MFS using a safe UI bundled with Companion (always works) and open imported files in ipfs-webui + copy shareable link to clipboard. File is provided by go-ipfs, so the link will work for everyone, and users with Companion will fetch it using true p2p. Sadly, we can't say the same about share.ipfs.io, which passes CID in  URL #fragment  and is crippled by js-ipfs-in-browser limitations (no dht, centralized webrtc signaling, gateway preload performance limited by non-deterministic load at the time).

Note that in the past, the context action "Share" on the Files screen of   ipfs-webui  actually copied link to share.ipfs.io :), but we changed that to direct gateway link  due to performance reasons at the time  (which are still not addressed IMO).

I'm open to ideas on how to integrate share.ipfs.io into existing import flow in a way that is compatible with the "offline" requirement. Rule of thumb: sharing with Companion has to work even when broken/malicious DNS/firewall is present.
